In [ ]:
# tables for performance metrics

In [ ]:
import pickle
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,  classification_report

In [ ]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent.parent))
from config1 import CLASSIFICATION_DATA, get_predictions_classes, classes54

In [4]:
p_model_outputs = CLASSIFICATION_DATA / "4.MODEL_PREDICTIONS"

In [ ]:


name_mapping = {
    'Acacia': r'$\it{Acacia}$', 'Acer': r'$\it{Acer}$', 'Alnus': r'$\it{Alnus}$',
    'Amarantaceae': 'Amarantaceae', 'Artemisia': r'$\it{Artemisia}$', 'Betulaceae': r'$\it{Betulaceae}$',
    'Brassicaceae': 'Brassicaceae', 'Buxus': r'$\it{Buxus}$',
    'Carduus': r'$\it{Carduus}$',  'Caryophyllaceae': 'Caryophyllaceae',
    'Cichorioideae': 'Cichorioideae',
    'Cupressaceae': r'$\it{Cupressaceae}$', 'Cyperaceae': 'Cyperaceae',
    'Echium': r'$\it{Echium}$', 'Ericaceae': 'Ericaceae', 'Fagus': r'$\it{Fagus}$',
    'Fraxinus': r'$\it{Fraxinus}$', 'FraxinusExcelsior': r'$\it{Fraxinus~excelsior}$',     'FraxinusOrnus': r'$\it{Fraxinus~ornus}$',
    'Gallium': r'$\it{Galium}$',     'Helianthemum': r'$\it{Helianthemum}$', 'Hypericum': r'$\it{Hypericum}$', 'IlexAquifolium': r'$\it{Ilex~aquifolium}$',
    'IndetBlurry': 'Indeterminate (blurry)', 'IndetCovered': 'Indeterminate (covered)',
    'Juglans': r'$\it{Juglans}$', 'Lamiaceae': 'Lamiaceae','Liliaceae': 'Liliaceae',  'Lycopodium': r'$\it{Lycopodium}$',
    'Moraceae': 'Moraceae', 'Morphotype1' : 'Morphotype 1', 'Morphotype2' : "Morphotype 2", 
    'Myrtaceae': 'Myrtaceae', 'NonPollen': 'Non-pollen', 'Olea': r'$\it{Olea}$',
    'Other': 'Other', 'Phillyrea': r'$\it{Phillyrea}$',
    'Pinaceae': 'Pinaceae', 'Pistacia': r'$\it{Pistacia}$', 'Plantago': r'$\it{Plantago}$',
    'Platanus': r'$\it{Platanus}$', 'Poaceae': 'Poaceae', 'PopulusSp': r'$\it{Populus}$',
    'QuercusDeciduous': r'$\it{Quercus~deciduous}$', 'QuercusIlex': r'$\it{Quercus~ilex}$',
    'Ranunculaceae': 'Ranunculaceae', 'Rhamnus': r'$\it{Rhamnus}$', 'Rosaceae': 'Rosaceae',
    'Rumex': r'$\it{Rumex}$', 'Salix': r'$\it{Salix}$', 'Sanguisorba': r'$\it{Sanguisorba}$',
    'Tilia': r'$\it{Tilia}$', 'Ulmus': r'$\it{Ulmus}$', 'Urtica': r'$\it{Urtica}$',
    "ViburnumSambucusTp" : r'$\it{Viburnum / Sambucus}$',
    'VitisF': r'$\it{Vitis}$ fertile', 'VitisS': r'$\it{Vitis}$ sterile', 'XanthiumAmbrosia':  r'$\it{Xanthium / Ambrosia}$',
}

# Performances and accuracy - all classes

In [6]:
def get_acc(true, pred, cval_id) :

    acc= accuracy_score(true, pred)
    report_dict = classification_report(true, pred,  zero_division=0, output_dict=True)
    df_classif = pd.DataFrame(report_dict).transpose()
    df_classif["support"] = [int(el) for el in df_classif["support"]]
    df_classif["cval_id"]=cval_id
    df_classif = df_classif.reset_index().rename(columns={'index': 'classe'})
    df_classif["classe"] = [el.split("_")[0] for el in df_classif["classe"]]
    df_overall_acc = df_classif[df_classif["classe"].isin(["accuracy", 'weighted avg', "macro avg"])]
    df_prclass = df_classif[~df_classif["classe"].isin(["accuracy", 'weighted avg', "macro avg"])]
    df_prclass["classe2"] = [name_mapping[el] for el in df_prclass["classe"]]
    return acc, df_overall_acc, df_prclass

In [ ]:
# df ENV , using only environmental images
envref="env"


all_overall_acc = []
all_prclass = []
check_env=True
for idx in [1,2,3,4,5,6,7,8,9,10]:
    cval_id = f'fold{idx}'
    true, pred, filename =  get_predictions_classes(cval_id, p_model_outputs, classes54, envref=envref)
    accuracy, df_overall_acc, df_prclass = get_acc(true, pred, cval_id)
    all_overall_acc.append(df_overall_acc)
    all_prclass.append(df_prclass)

df_overall_acc_long = pd.concat(all_overall_acc, ignore_index=True)
df_prclass_long = pd.concat(all_prclass, ignore_index=True)

n_folds = df_prclass_long['cval_id'].nunique()
agg_df_env = df_prclass_long.groupby('classe')[['precision', 'recall', 'f1-score', 'support']].agg(['mean', 'std'])

agg_df_env[('precision', 'se')] = agg_df_env[('precision', 'std')] / np.sqrt(n_folds)
agg_df_env[('recall', 'se')] = agg_df_env[('recall', 'std')] / np.sqrt(n_folds)
agg_df_env[('f1-score', 'se')] = agg_df_env[('f1-score', 'std')] / np.sqrt(n_folds)
agg_df_env[('support', 'se')] = agg_df_env[('support', 'std')] / np.sqrt(n_folds)

agg_df_env = agg_df_env.drop(columns=[('precision', 'std'), ('recall', 'std'), ('f1-score', 'std'), ('support', 'std')])

agg_df_env.columns = ['_'.join(map(str, col)).strip() for col in agg_df_env.columns.values]
agg_df_env=agg_df_env.reset_index()

agg_df_env.head()

,classe,precision_mean,recall_mean,f1-score_mean,support_mean,precision_se,recall_se,f1-score_se,support_se
0,Acacia,0.000000,0.000000,0.000000,1.0,NaN,NaN,NaN,NaN
1,Acer,0.889318,0.943056,0.913723,8.9,0.027117,0.019027,0.019715,0.100000
2,Alnus,0.955909,0.941818,0.946711,10.5,0.019306,0.021776,0.014965,0.166667
3,Amarantaceae,0.957778,0.951389,0.950289,8.1,0.022819,0.027252,0.015940,0.100000
4,Artemisia,0.910000,0.841667,0.847857,3.3,0.060461,0.072913,0.060102,0.152753

In [ ]:
# df REF, using both reference and environmental images
envref="ref"


all_overall_acc = []
all_prclass = []
check_env=True
for idx in [1,2,3,4,5,6,7,8,9,10]:
    cval_id = f'fold{idx}'
    true, pred, filename =  get_predictions_classes(cval_id, p_model_outputs, classes54, envref=envref)
    accuracy, df_overall_acc, df_prclass = get_acc(true, pred, cval_id)
    all_overall_acc.append(df_overall_acc)
    all_prclass.append(df_prclass)

df_overall_acc_long = pd.concat(all_overall_acc, ignore_index=True)
df_prclass_long = pd.concat(all_prclass, ignore_index=True)

n_folds = df_prclass_long['cval_id'].nunique()
agg_df_ref = df_prclass_long.groupby('classe')[['precision', 'recall', 'f1-score', 'support']].agg(['mean', 'std'])

agg_df_ref[('precision', 'se')] = agg_df_ref[('precision', 'std')] / np.sqrt(n_folds)
agg_df_ref[('recall', 'se')] = agg_df_ref[('recall', 'std')] / np.sqrt(n_folds)
agg_df_ref[('f1-score', 'se')] = agg_df_ref[('f1-score', 'std')] / np.sqrt(n_folds)
agg_df_ref[('support', 'se')] = agg_df_ref[('support', 'std')] / np.sqrt(n_folds)

agg_df_ref = agg_df_ref.drop(columns=[('precision', 'std'), ('recall', 'std'), ('f1-score', 'std'), ('support', 'std')])

agg_df_ref.columns = ['_'.join(map(str, col)).strip() for col in agg_df_ref.columns.values]
agg_df_ref=agg_df_ref.reset_index()

agg_df_ref.head()

,classe,precision_mean,recall_mean,f1-score_mean,support_mean,precision_se,recall_se,f1-score_se,support_se
0,Acacia,1.000000,0.983333,0.990909,5.0,0.000000,0.016667,0.009091,0.149071
1,Acer,0.982025,0.991409,0.986659,93.1,0.003844,0.002137,0.002406,0.179505
2,Alnus,0.983854,0.976623,0.980110,55.7,0.004113,0.005436,0.003295,0.152753
3,Amarantaceae,0.998012,0.998002,0.998000,200.0,0.001097,0.001105,0.000624,0.149071
4,Artemisia,0.996887,0.996050,0.996452,126.8,0.002075,0.001770,0.001369,0.249444

In [10]:
#get df1 with all values o precision recall f1-scre *100 and rounded to 0.1
# 2SE
agg_df_env["precision_mean"] = (agg_df_env["precision_mean"]*100).round(1)
agg_df_env["recall_mean"] = (agg_df_env["recall_mean"]*100).round(1)
agg_df_env["f1-score_mean"] = (agg_df_env["f1-score_mean"]*100).round(1)
agg_df_env["precision_se"] = (agg_df_env["precision_se"]*100*2).round(1)
agg_df_env["recall_se"] = (agg_df_env["recall_se"]*100*2).round(1)
agg_df_env["f1-score_se"] = (agg_df_env["f1-score_se"]*100*2).round(1)
agg_df_env.head()

agg_df_ref["precision_mean"] = (agg_df_ref["precision_mean"]*100).round(1)
agg_df_ref["recall_mean"] = (agg_df_ref["recall_mean"]*100).round(1)
agg_df_ref["f1-score_mean"] = (agg_df_ref["f1-score_mean"]*100).round(1)
agg_df_ref["precision_se"] = (agg_df_ref["precision_se"]*100*2).round(1)
agg_df_ref["recall_se"] = (agg_df_ref["recall_se"]*100*2).round(1)
agg_df_ref["f1-score_se"] = (agg_df_ref["f1-score_se"]*100*2).round(1)
agg_df_ref.head()

,classe,precision_mean,recall_mean,f1-score_mean,support_mean,precision_se,recall_se,f1-score_se,support_se
0,Acacia,100.0,98.3,99.1,5.0,0.0,3.3,1.8,0.149071
1,Acer,98.2,99.1,98.7,93.1,0.8,0.4,0.5,0.179505
2,Alnus,98.4,97.7,98.0,55.7,0.8,1.1,0.7,0.152753
3,Amarantaceae,99.8,99.8,99.8,200.0,0.2,0.2,0.1,0.149071
4,Artemisia,99.7,99.6,99.6,126.8,0.4,0.4,0.3,0.249444

In [11]:
# for all classes represented, sorted in alphabetcic (a->z), write a latex line with class name, precision+-SE of df1, recall+-SE of df1, f1-score+-SE of df1, support of df1, precision+-SE of df2, recall+-SE of df2, f1-score+-SE of df2, support of df2, with mean and SE (2SE) for each metric

latex_rows = []

print('Full dataset (ref and env) & environment only \\\\')
print(("Classe & Precision (mean ± 2SE) & Recall (mean ± 2SE) & F1-score (mean ± 2SE) & Support (mean ± 2SE) & Precision (mean ± 2SE) & Recall (mean ± 2SE) & F1-score (mean ± 2SE) & Support (mean ± 2SE) \\\\"))
for _, row1 in agg_df_ref.iterrows():
    class_name = row1["classe"]
    try:
        row2 = agg_df_env[agg_df_env["classe"] == class_name].iloc[0]  # Get the corresponding row in df2
        line = f"{class_name} & {row1['precision_mean']}+/-{row1['precision_se']} & {row1['recall_mean']}+/-{row1['recall_se']} & {row1['f1-score_mean']}+/-{row1['f1-score_se']} & {row1['support_mean']} & {row2['precision_mean']}+/-{row2['precision_se']} & {row2['recall_mean']}+/-{row2['recall_se']} & {row2['f1-score_mean']}+/-{row2['f1-score_se']} & {row2['support_mean']} \\\\"

    except IndexError:
        line = f"{class_name} & {row1['precision_mean']}+/-{row1['precision_se']} & {row1['recall_mean']}+/-{row1['recall_se']} & {row1['f1-score_mean']}+/-{row1['f1-score_se']} & {row1['support_mean']} & NA & NA & NA & NA \\\\"

    latex_rows.append(line)
latex_table = "\n".join(latex_rows)
print(latex_table)

Full dataset (ref and env) & environment only \\
Classe & Precision (mean ± 2SE) & Recall (mean ± 2SE) & F1-score (mean ± 2SE) & Support (mean ± 2SE) & Precision (mean ± 2SE) & Recall (mean ± 2SE) & F1-score (mean ± 2SE) & Support (mean ± 2SE) \\
Acacia & 100.0+/-0.0 & 98.3+/-3.3 & 99.1+/-1.8 & 5.0 & 0.0+/-nan & 0.0+/-nan & 0.0+/-nan & 1.0 \\
Acer & 98.2+/-0.8 & 99.1+/-0.4 & 98.7+/-0.5 & 93.1 & 88.9+/-5.4 & 94.3+/-3.8 & 91.4+/-3.9 & 8.9 \\
Alnus & 98.4+/-0.8 & 97.7+/-1.1 & 98.0+/-0.7 & 55.7 & 95.6+/-3.9 & 94.2+/-4.4 & 94.7+/-3.0 & 10.5 \\
Amarantaceae & 99.8+/-0.2 & 99.8+/-0.2 & 99.8+/-0.1 & 200.0 & 95.8+/-4.6 & 95.1+/-5.5 & 95.0+/-3.2 & 8.1 \\
Artemisia & 99.7+/-0.4 & 99.6+/-0.4 & 99.6+/-0.3 & 126.8 & 91.0+/-12.1 & 84.2+/-14.6 & 84.8+/-12.0 & 3.3 \\
Betulaceae & 99.2+/-0.3 & 99.1+/-0.4 & 99.1+/-0.2 & 200.0 & 95.4+/-1.8 & 93.8+/-4.0 & 94.5+/-2.2 & 19.6 \\
Brassicaceae & 99.1+/-0.5 & 99.5+/-0.4 & 99.3+/-0.4 & 124.6 & 95.2+/-2.9 & 96.7+/-2.9 & 95.9+/-2.5 & 18.1 \\
Buxus & 98.6+/-0.6 & 99.7+/-0.5 & 99.1+/-0.4 & 116.7 & 98.6+/-0.6 & 99.5+/-0.6 & 99.0+/-0.5 & 83.7 \\
Carduus & 99.8+/-0.3 & 99.6+/-0.3 & 99.7+/-0.2 & 98.3 & 97.6+/-3.2 & 94.5+/-4.5 & 95.8+/-2.3 & 7.4 \\
Caryophyllaceae & 100.0+/-0.0 & 99.4+/-0.5 & 99.7+/-0.2 & 68.5 & NA & NA & NA & NA \\
Cichorioideae & 99.7+/-0.4 & 99.7+/-0.4 & 99.7+/-0.2 & 119.4 & 96.7+/-3.7 & 97.0+/-4.3 & 96.6+/-2.6 & 10.2 \\
Cupressaceae & 97.1+/-1.0 & 97.5+/-0.7 & 97.3+/-0.6 & 200.0 & 95.9+/-1.5 & 97.5+/-1.3 & 96.6+/-0.9 & 91.4 \\
Cyperaceae & 97.0+/-2.4 & 89.1+/-3.3 & 92.7+/-1.9 & 13.8 & 100.0+/-0.0 & 76.7+/-5.6 & 86.5+/-3.9 & 5.2 \\
Echium & 99.2+/-0.8 & 99.7+/-0.6 & 99.4+/-0.5 & 35.2 & 100.0+/-nan & 100.0+/-nan & 100.0+/-nan & 1.0 \\
Ericaceae & 98.8+/-1.0 & 99.4+/-0.8 & 99.1+/-0.7 & 32.9 & 96.1+/-4.0 & 96.7+/-4.4 & 96.1+/-2.7 & 6.3 \\
Fagus & 91.7+/-8.6 & 92.5+/-10.7 & 90.7+/-8.1 & 2.9 & 30.0+/-28.3 & 40.0+/-34.6 & 33.3+/-29.8 & 0.8 \\
FraxinusExcelsior & 91.0+/-3.7 & 86.6+/-2.2 & 88.7+/-2.3 & 29.2 & 91.3+/-4.6 & 94.7+/-2.9 & 92.7+/-2.5 & 22.5 \\
FraxinusOrnus & 96.1+/-0.7 & 96.3+/-0.7 & 96.2+/-0.5 & 122.5 & 43.3+/-19.0 & 26.7+/-12.2 & 31.0+/-12.6 & 5.4 \\
Gallium & 98.3+/-1.4 & 97.6+/-1.4 & 97.9+/-1.3 & 57.4 & 87.0+/-8.5 & 83.7+/-11.1 & 84.9+/-9.2 & 5.7 \\
IndetBlurry & 97.8+/-1.3 & 97.0+/-1.4 & 97.4+/-1.0 & 44.0 & 98.4+/-1.0 & 97.0+/-1.4 & 97.7+/-1.0 & 44.0 \\
IndetCovered & 88.9+/-1.1 & 85.8+/-2.7 & 87.3+/-1.7 & 48.7 & 90.5+/-1.4 & 85.8+/-2.7 & 88.1+/-1.6 & 48.7 \\
Juglans & 99.5+/-1.0 & 98.9+/-1.4 & 99.2+/-0.8 & 19.2 & 64.3+/-30.1 & 71.4+/-30.9 & 66.7+/-29.8 & 1.0 \\
Lamiaceae & 97.4+/-2.6 & 95.7+/-3.8 & 96.5+/-2.8 & 11.1 & 76.7+/-26.4 & 70.0+/-26.7 & 71.3+/-25.3 & 1.6 \\
Liliaceae & 95.3+/-1.5 & 97.8+/-1.1 & 96.5+/-1.1 & 45.4 & 10.3+/-11.4 & 30.0+/-30.6 & 15.0+/-16.1 & 0.6 \\
Lycopodium & 99.3+/-0.4 & 99.5+/-0.4 & 99.4+/-0.3 & 149.9 & 99.6+/-0.4 & 99.5+/-0.4 & 99.5+/-0.3 & 149.9 \\
Moraceae & 99.4+/-1.1 & 96.1+/-3.7 & 97.7+/-2.1 & 18.0 & NA & NA & NA & NA \\
Morphotype1 & 98.8+/-0.6 & 98.6+/-0.7 & 98.7+/-0.4 & 200.0 & 87.0+/-8.1 & 79.9+/-10.3 & 82.2+/-8.0 & 8.4 \\
Morphotype2 & 98.8+/-0.9 & 99.6+/-0.5 & 99.2+/-0.6 & 49.5 & 96.3+/-5.0 & 98.6+/-2.9 & 97.2+/-3.0 & 6.5 \\
Myrtaceae & 99.5+/-1.1 & 100.0+/-0.0 & 99.7+/-0.5 & 18.4 & 0.0+/-nan & 0.0+/-nan & 0.0+/-nan & 0.0 \\
NonPollen & 95.4+/-1.0 & 93.3+/-1.0 & 94.4+/-0.8 & 182.7 & 95.3+/-1.3 & 94.4+/-1.1 & 94.8+/-1.0 & 142.0 \\
Olea & 98.9+/-1.0 & 98.8+/-0.8 & 98.8+/-0.8 & 130.0 & 96.1+/-3.5 & 95.1+/-3.2 & 95.5+/-2.9 & 32.6 \\
Other & 84.5+/-10.5 & 66.1+/-8.7 & 72.9+/-7.7 & 8.0 & 83.8+/-10.0 & 62.6+/-10.2 & 70.1+/-8.4 & 6.8 \\
Phillyrea & 96.5+/-0.8 & 97.5+/-0.6 & 97.0+/-0.5 & 200.0 & 79.3+/-4.1 & 85.5+/-4.2 & 82.1+/-3.4 & 26.3 \\
Pinaceae & 98.8+/-0.5 & 99.7+/-0.3 & 99.3+/-0.3 & 128.2 & 99.1+/-0.6 & 100.0+/-0.0 & 99.5+/-0.3 & 95.4 \\
Pistacia & 98.1+/-0.9 & 98.0+/-1.0 & 98.0+/-0.8 & 104.6 & 94.6+/-3.4 & 94.3+/-2.9 & 94.4+/-2.4 & 23.0 \\
Plantago & 99.2+/-0.5 & 99.6+/-0.3 & 99.4+/-0.2 & 182.5 & 97.6+/-2.2 & 98.3+/-1.8 & 97.8+/-1.2 & 34.5 \\
Platanus & 98.1+/-0.9 & 98.9+/-0.9 & 98.4+/-0.5 & 60.9 & 94.6+/-4.5 & 92.9+/-6.4 & 93.4+/-4.2 & 7.0 \\
Poaceae & 98.7+/-0.4 & 99.2+/-0.5 & 98.9+/-0.3 & 200.0 & 97.7+/-0.7 & 98.5+/-1.1 & 98.1+/-0.6 & 95.6 \\
PopulusSp & 98.6+/-0.5 & 99.5+/-0.5 & 99.0+/-0.4 & 167.8 & 0.0+/-nan & 0.0+/-nan & 0.0+/-nan & 0.0 \\
QuercusDeciduous & 97.4+/-0.7 & 97.0+/-0.6 & 97.2+/-0.5 & 200.0 & 78.6+/-7.3 & 73.6+/-6.4 & 75.5+/-5.7 & 12.1 \\
QuercusIlex & 96.5+/-0.8 & 97.8+/-0.6 & 97.1+/-0.4 & 200.0 & 92.5+/-2.0 & 95.7+/-1.4 & 94.0+/-0.8 & 67.7 \\
Ranunculaceae & 98.7+/-1.4 & 98.1+/-2.5 & 98.3+/-1.3 & 21.3 & 65.0+/-26.0 & 80.0+/-26.7 & 70.0+/-25.2 & 1.0 \\
Rhamnus & 98.3+/-1.5 & 95.8+/-2.6 & 97.0+/-1.6 & 35.6 & 95.9+/-3.4 & 89.4+/-7.1 & 92.2+/-4.6 & 9.6 \\
Rosaceae & 97.2+/-0.6 & 97.4+/-0.8 & 97.3+/-0.4 & 200.0 & 89.6+/-2.0 & 90.9+/-3.1 & 90.2+/-1.8 & 38.5 \\
Rumex & 99.7+/-0.3 & 98.7+/-0.5 & 99.2+/-0.3 & 107.3 & 96.0+/-5.3 & 78.7+/-7.3 & 85.8+/-5.1 & 5.2 \\
Salix & 99.1+/-1.2 & 95.3+/-2.0 & 97.1+/-1.2 & 23.3 & 14.3+/-23.9 & 14.3+/-23.9 & 14.3+/-23.9 & 1.0 \\
Sanguisorba & 91.6+/-5.7 & 84.7+/-7.8 & 87.3+/-5.0 & 5.8 & 90.2+/-6.7 & 87.5+/-6.9 & 88.3+/-5.2 & 4.8 \\
Tilia & 97.5+/-5.0 & 93.0+/-10.3 & 94.9+/-8.1 & 5.1 & 0.0+/-nan & 0.0+/-nan & 0.0+/-nan & 1.0 \\
Ulmus & 99.6+/-0.7 & 99.6+/-0.7 & 99.6+/-0.7 & 28.7 & 96.7+/-6.7 & 100.0+/-0.0 & 98.0+/-4.0 & 2.1 \\
Urtica & 99.4+/-0.4 & 99.6+/-0.4 & 99.5+/-0.2 & 125.5 & 85.7+/-15.4 & 100.0+/-0.0 & 90.5+/-10.3 & 1.0 \\
ViburnumSambucusTp & 96.7+/-2.0 & 96.2+/-2.3 & 96.4+/-1.5 & 23.8 & 68.3+/-20.8 & 65.0+/-21.3 & 62.7+/-16.7 & 2.1 \\
VitisF & 98.7+/-0.4 & 99.1+/-0.4 & 98.9+/-0.3 & 200.0 & 97.8+/-1.4 & 97.9+/-0.9 & 97.8+/-0.6 & 57.2 \\
VitisS & 98.9+/-0.4 & 99.2+/-0.4 & 99.1+/-0.3 & 121.3 & 94.3+/-2.8 & 95.1+/-3.0 & 94.5+/-1.6 & 18.3 \\
XanthiumAmbrosia & 99.8+/-0.2 & 100.0+/-0.0 & 99.9+/-0.1 & 200.0 & 91.5+/-7.0 & 100.0+/-0.0 & 95.2+/-3.9 & 3.4 \\